name: Auto-refresh all Prikkrs

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
      KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
    steps:
      - name: Discover all meta:* keys via KV REST and call refresh
        shell: bash
        run: |
          set -euo pipefail

          cursor=0
          ids=()

          while : ; do
            if [[ "$KV_REST_API_URL" == *"upstash.io"* ]]; then
              # --- Upstash shape ---
              RESP=$(curl -fsS \
                -H "Authorization: Bearer $KV_REST_API_TOKEN" \
                "$KV_REST_API_URL/scan/${cursor}?match=meta:*&count=200")
              new_cursor=$(echo "$RESP" | jq -r '.result[0]')
              keys=$(echo "$RESP" | jq -r '.result[1][]?')
            else
              # --- Vercel KV shape ---
              RESP=$(curl -fsS \
                -H "Authorization: Bearer $KV_REST_API_TOKEN" \
                "$KV_REST_API_URL/scan?cursor=${cursor}&match=meta:*&count=200")
              new_cursor=$(echo "$RESP" | jq -r '.cursor // .Cursor // "0"')
              keys=$(echo "$RESP" | jq -r '.keys[]?')
            fi

            while IFS= read -r k; do
              [[ -n "$k" ]] || continue
              ids+=("${k#meta:}")
            done <<< "$keys"

            [[ -z "$new_cursor" || "$new_cursor" == "0" || "$new_cursor" == "null" ]] && break
            cursor="$new_cursor"
          done

          echo "Found ${#ids[@]} IDs"

          for id in "${ids[@]}"; do
            url="$BASE_URL/api/cron/refresh/$CRON_SECRET?id=$id"
            echo "GET $url"
            curl -fsS "$url" >/dev/null
            echo " ok"
          done
